### ISSUE TITLE
Wrong headers for json rpc

### ISSUE THREAD

**Issue by chrispaterson** [andyfowler/node-jsonrpc-client#1]
I'm not sure why this worked or didn't...  I kept getting a "Cannot POST /" error when attempting to connect to a JSON RPC2 server on my localhost (just on a different port).  Turns out, line 13 of /lib/index.js has .header('Accept', 'application/json').  By adding .header('Content-Type', 'application/json') I was able to get it to work.  Is this module tested?  I'm not sure why it would work without sending a content type...

**Comment by andyfowler** [comment]
Hey Chris,

It has indeed been tested -- we use this module in production against a PHP Zend Framework JSON-RPC server, which must be sloppy enough to not care about `Content-Type`. Feel free to send a pull request to add the `Content-Type` -- I imagine that the `Accept` header should still exist. Thanks!

**Comment by chrispaterson** [comment]
Interesting, I'm running against a node jsonrpc server, it must care!  I'll submit the pull request in just a few moments
